# Generated by Django 4.0.6 on 2022-07-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nalaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_nalaza', models.CharField(max_length=50)),
                ('razlog_dolaska', models.TextField(max_length=200)),
                ('anamneza', models.TextField(max_length=200)),
                ('terapija', models.TextField(max_length=200)),
                ('zaključak', models.TextField(max_length=200)),
                ('naziv_radilišta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nalaz', to='App.radilišta')),
                ('zaposlenik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nalaz', to=settings.AUTH_USER_MODEL)),
                ('zaposlenik2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nalaz2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistarPacijenata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('broj_telefona', models.IntegerField()),
                ('adresa', models.CharField(max_length=50)),
                ('status_osiguranja', models.CharField(blank=True, choices=[('DA', 'Važeće'), ('NE', 'Nevažeće')], max_length=50)),
                ('datum_police_osiguranja', models.DateField()),
                ('nalazi', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registar_nalazi', to='App.nalaz')),
            ],
        ),
    ]
