# Generated by Django 4.0.6 on 2022-07-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_registarpacijenata_mbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='adresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='broj_telefona',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_police_osiguranja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
