# Generated by Django 4.0.6 on 2022-07-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_registarpacijenata_datum_rođenja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='nalazi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registar_nalazi', to='App.nalaz'),
        ),
    ]
