# Generated by Django 4.0.6 on 2022-07-07 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_registarpacijenata_mbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='MBO',
            field=models.IntegerField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
