# Generated by Django 4.0.6 on 2022-07-07 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_registarpacijenata_mbo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='MBO',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_police_osiguranja',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
