# Generated by Django 4.0.6 on 2022-07-07 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_registarpacijenata_mbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
