# Generated by Django 4.0.6 on 2022-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_registarpacijenata_datum_rođenja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
