# Generated by Django 4.0.6 on 2022-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_registarpacijenata_datum_rođenja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='MBO',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
