# Generated by Django 4.0.6 on 2022-07-09 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_posjeta_nalaz_alter_posjeta_utrošak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posjeta',
            name='utrošak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posjeta', to='App.utrošak'),
        ),
    ]
