# Generated by Django 4.0.6 on 2022-07-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_šifrarnikutrošak_naziv'),
    ]

    operations = [
        migrations.AddField(
            model_name='posjeta',
            name='količina_utroška',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posjeta',
            name='utrošak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posjeta', to='App.šifrarnikutrošak'),
        ),
        migrations.DeleteModel(
            name='Utrošak',
        ),
    ]
