# Generated by Django 4.0.6 on 2022-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_registarpacijenata_mbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='MBO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
