# Generated by Django 4.0.6 on 2022-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_registarpacijenata_mbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uputnice',
            name='tip',
            field=models.CharField(choices=[('A1', 'Konzilijarni pregled'), ('A2', 'Kontrolni konzilijarni pregled'), ('C1', 'Pregled i cjelovita obrada u specijalističkoj zdravstvenoj zaštiti'), ('C2', 'Pregled i obrada kroz Objedinjeni hitni bolnički prijam'), ('D1', 'Ambulantno liječenje'), ('D2', ' Dnevna bolnica'), ('NEMA', 'Bez_uputnice')], max_length=50),
        ),
    ]
