# Generated by Django 4.0.6 on 2022-07-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_uputnice_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posjeta',
            name='količina_utroška',
        ),
        migrations.RemoveField(
            model_name='posjeta',
            name='utrošak',
        ),
        migrations.CreateModel(
            name='Utrošak_posjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('količina_utroška', models.IntegerField(blank=True, null=True)),
                ('posjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utrošak_posjeta', to='App.posjeta')),
                ('utrošak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utrošak_posjeta', to='App.šifrarnikutrošak')),
            ],
        ),
    ]
