# Generated by Django 4.0.6 on 2022-07-11 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_remove_posjeta_količina_utroška_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blagajna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cijena', models.IntegerField()),
                ('posjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blagajna', to='App.posjeta')),
                ('zaposlenik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blagajna', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
