# Generated by Django 4.0.6 on 2022-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_blagajna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blagajna',
            name='cijena',
            field=models.FloatField(),
        ),
    ]
