# Generated by Django 4.0.6 on 2022-07-16 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_posjeta_status_otpusta_posjeta_vrijeme_otupusta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posjeta',
            name='nalaz',
        ),
        migrations.RemoveField(
            model_name='registarpacijenata',
            name='nalazi',
        ),
        migrations.AddField(
            model_name='nalaz',
            name='posjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nalazi', to='App.posjeta'),
        ),
        migrations.AlterField(
            model_name='nalaz',
            name='zaposlenik2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nalaz2', to=settings.AUTH_USER_MODEL),
        ),
    ]
