# Generated by Django 4.0.6 on 2022-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_posjeta_nalaz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nalaz',
            name='dijagnoza',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='nalaz',
            name='anamneza',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nalaz',
            name='razlog_dolaska',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nalaz',
            name='terapija',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nalaz',
            name='zaključak',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
