# Generated by Django 4.0.6 on 2022-07-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_nalaz_dijagnoza_alter_nalaz_anamneza_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posjeta',
            old_name='vrijeme_otupusta',
            new_name='vrijeme_otpusta',
        ),
    ]
