# Generated by Django 4.0.6 on 2022-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_rename_vrijeme_otupusta_posjeta_vrijeme_otpusta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_police_osiguranja',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='registarpacijenata',
            name='datum_rođenja',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
